version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql2

volumes:
  mysql_data: